default: &default
  adapter: postgresql
  encoding: unicode
  username: moe
  password: 451175
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rate_dev

test:
  <<: *default
  database: rate_test

# production:
#   <<: *default
#   database: rate_prod

# production:
# url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: <%= ENV['RDS_DATABASE'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>
  port: 5432